In [1]:
print("Python is working")

Python is working

In [18]:
# importing pandas library for dataframe operations
import pandas as pd

# importing numpy library for numerical operations
import numpy as np

In [19]:
# creating employee dataframe with details
employee = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],  # employee id
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],  # full name
    "Gender": ["M","F","M","F","F"],  # gender
    "City": ["Paris","London","Berlin","Newyork","Madrid"],  # city
    "Age": [25,27,29,31,30]  # age
})

# displaying dataframe
employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [20]:
# creating seniority dataframe
seniority = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],  # employee id
    "Designation Level": [2,2,3,2,3]  # designation level
})

# displaying dataframe
seniority

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [21]:
# creating project dataframe with project details
project = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],  # employee id
    "Project": ["Project1","Project2","Project3","Project4","Project5","Project6","Project7","Project8","Project9","Project10","Project11","Project12","Project13","Project14"],  # project name
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],  # project cost
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]  # project status
})

# display dataframe
project

      ID    Project       Cost    Status
0   A001   Project1  1002000.0  Finished
1   A002   Project2  2000000.0   Ongoing
2   A003   Project3  4500000.0  Finished
3   A004   Project4  5500000.0   Ongoing
4   A005   Project5        NaN  Finished
5   A002   Project6   680000.0    Failed
6   A005   Project7   400000.0  Finished
7   A003   Project8   350000.0    Failed
8   A001   Project9        NaN   Ongoing
9   A003  Project10   300000.0  Finished
10  A001  Project11  2000000.0    Failed
11  A004  Project12  1000000.0   Ongoing
12  A004  Project13  3000000.0  Finished
13  A005  Project14   200000.0  Finished

In [22]:
# saving employee dataframe to csv file
employee.to_csv("employee.csv", index=False)

# saving seniority dataframe to csv file 
seniority.to_csv("seniority.csv", index=False)

# saving project dataframe to csv file
project.to_csv("project.csv", index=False)

In [23]:
# reading project csv file
project = pd.read_csv("project.csv")

# display dataframe
project

      ID    Project       Cost    Status
0   A001   Project1  1002000.0  Finished
1   A002   Project2  2000000.0   Ongoing
2   A003   Project3  4500000.0  Finished
3   A004   Project4  5500000.0   Ongoing
4   A005   Project5        NaN  Finished
5   A002   Project6   680000.0    Failed
6   A005   Project7   400000.0  Finished
7   A003   Project8   350000.0    Failed
8   A001   Project9        NaN   Ongoing
9   A003  Project10   300000.0  Finished
10  A001  Project11  2000000.0    Failed
11  A004  Project12  1000000.0   Ongoing
12  A004  Project13  3000000.0  Finished
13  A005  Project14   200000.0  Finished

In [24]:
# converting cost column into list
cost_list = project["Cost"].tolist()

# loop through list
for i in range(len(cost_list)):
    
    # check if value is missing
    if pd.isna(cost_list[i]):
        
        # calculate running average of previous values
        avg = np.nanmean(cost_list[:i])
        
        # replace missing value with average
        cost_list[i] = avg

# assign updated values back to dataframe
project["Cost"] = cost_list

# display updated dataframe
project

      ID    Project       Cost    Status
0   A001   Project1  1002000.0  Finished
1   A002   Project2  2000000.0   Ongoing
2   A003   Project3  4500000.0  Finished
3   A004   Project4  5500000.0   Ongoing
4   A005   Project5  3250500.0  Finished
5   A002   Project6   680000.0    Failed
6   A005   Project7   400000.0  Finished
7   A003   Project8   350000.0    Failed
8   A001   Project9  2210312.5   Ongoing
9   A003  Project10   300000.0  Finished
10  A001  Project11  2000000.0    Failed
11  A004  Project12  1000000.0   Ongoing
12  A004  Project13  3000000.0  Finished
13  A005  Project14   200000.0  Finished

In [25]:
# reading employee csv
employee = pd.read_csv("employee.csv")

# split name into first and last name
employee[["First Name","Last Name"]] = employee["Name"].str.split(" ", expand=True)

# remove original name column
employee.drop("Name", axis=1, inplace=True)

# display dataframe
employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [26]:
# reading seniority csv
seniority = pd.read_csv("seniority.csv")

# merge employee and seniority
final = pd.merge(employee, seniority, on="ID")

# merge above result with project
final = pd.merge(final, project, on="ID")

# display final dataframe
final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project1,1002000.0,Finished
1,A001,M,Paris,25,John,Alter,2,Project9,2210312.5,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project11,2000000.0,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project2,2000000.0,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project6,680000.0,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project3,4500000.0,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project8,350000.0,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project10,300000.0,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project4,5500000.0,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project12,1000000.0,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project13,3000000.0,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project5,3250500.0,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project7,400000.0,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project14,200000.0,Finished

In [27]:
# giving 5% bonus if project finished
final["Bonus"] = np.where(final["Status"]=="Finished", final["Cost"]*0.05, 0)

# display dataframe
final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project1,1002000.0,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project9,2210312.5,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project11,2000000.0,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project2,2000000.0,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project6,680000.0,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project3,4500000.0,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project8,350000.0,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project10,300000.0,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project4,5500000.0,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project12,1000000.0,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project13,3000000.0,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project5,3250500.0,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project7,400000.0,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project14,200000.0,Finished,10000.0

In [28]:
# increase designation level by 1 if project failed
final.loc[final["Status"]=="Failed", "Designation Level"] += 1

# remove employees whose level greater than 4
final = final[final["Designation Level"]<=4]

# display dataframe
final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project1,1002000.0,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project9,2210312.5,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,3,Project11,2000000.0,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project2,2000000.0,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,3,Project6,680000.0,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project3,4500000.0,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,4,Project8,350000.0,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project10,300000.0,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project4,5500000.0,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project12,1000000.0,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project13,3000000.0,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project5,3250500.0,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project7,400000.0,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project14,200000.0,Finished,10000.0

In [29]:
# add Mr or Mrs based on gender
final["First Name"] = np.where(final["Gender"]=="M",
                               "Mr. " + final["First Name"],
                               "Mrs. " + final["First Name"])

# remove gender column
final.drop("Gender", axis=1, inplace=True)

# display dataframe
final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project1,1002000.0,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project9,2210312.5,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project11,2000000.0,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project6,680000.0,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project3,4500000.0,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project8,350000.0,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project10,300000.0,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project13,3000000.0,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project5,3250500.0,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project7,400000.0,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project14,200000.0,Finished,10000.0

In [30]:
# promote employees whose age above 29
final.loc[final["Age"]>29, "Designation Level"] -= 1

# display dataframe
final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project1,1002000.0,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project9,2210312.5,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project11,2000000.0,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project6,680000.0,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project3,4500000.0,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project8,350000.0,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project10,300000.0,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project13,3000000.0,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project5,3250500.0,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project7,400000.0,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project14,200000.0,Finished,10000.0

In [31]:
# calculate total cost per employee
TotalProjCost = final.groupby(["ID","First Name"])["Cost"].sum().reset_index()

# rename cost column
TotalProjCost.rename(columns={"Cost":"Total Cost"}, inplace=True)

# display dataframe
TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

In [32]:
# filter employees whose city contains letter o
final[final["City"].str.contains("o", case=False)]

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project13,3000000.0,Finished,150000.0